export const dynamic = "force-dynamic";
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAdmin, isAuthUser } from "@/lib/auth";

const layers = [
  { index: 0, slug: "l0", nameJa: "L0 生成位相", descriptionJa: "存在の根源的な発生・出現・潜在性の位相", colorClass: "layer-0" },
  { index: 1, slug: "l1", nameJa: "L1 可能性空間", descriptionJa: "選択肢・分岐・確率・仮説の空間", colorClass: "layer-1" },
  { index: 2, slug: "l2", nameJa: "L2 時間因果", descriptionJa: "原因・結果・時系列・プロセスの連鎖", colorClass: "layer-2" },
  { index: 3, slug: "l3", nameJa: "L3 主体心理", descriptionJa: "主観・感情・動機・意図・認知の層", colorClass: "layer-3" },
  { index: 4, slug: "l4", nameJa: "L4 社会評価", descriptionJa: "規範・価値判断・社会的意味・評判の層", colorClass: "layer-4" },
  { index: 5, slug: "l5", nameJa: "L5 制度形式", descriptionJa: "法・制度・手続き・形式的ルールの層", colorClass: "layer-5" },
];

// 1000語規模の辞書データ
const dictionaryTerms: { layerSlug: string; term: string; weight: number; isNegation?: boolean }[] = [
  // ===== L0 生成位相 =====
  { layerSlug: "l0", term: "生成", weight: 1.5 },
  { layerSlug: "l0", term: "発生", weight: 1.4 },
  { layerSlug: "l0", term: "存在", weight: 1.3 },
  { layerSlug: "l0", term: "潜在", weight: 1.4 },
  { layerSlug: "l0", term: "根源", weight: 1.5 },
  { layerSlug: "l0", term: "位相", weight: 1.3 },
  { layerSlug: "l0", term: "出現", weight: 1.3 },
  { layerSlug: "l0", term: "本質", weight: 1.4 },
  { layerSlug: "l0", term: "起源", weight: 1.4 },
  { layerSlug: "l0", term: "創出", weight: 1.5 },
  { layerSlug: "l0", term: "発現", weight: 1.3 },
  { layerSlug: "l0", term: "顕現", weight: 1.4 },
  { layerSlug: "l0", term: "潜勢", weight: 1.3 },
  { layerSlug: "l0", term: "実体", weight: 1.2 },
  { layerSlug: "l0", term: "本源", weight: 1.4 },
  { layerSlug: "l0", term: "発露", weight: 1.3 },
  { layerSlug: "l0", term: "萌芽", weight: 1.4 },
  { layerSlug: "l0", term: "胚胎", weight: 1.3 },
  { layerSlug: "l0", term: "源泉", weight: 1.3 },
  { layerSlug: "l0", term: "誕生", weight: 1.2 },
  { layerSlug: "l0", term: "創造", weight: 1.4 },
  { layerSlug: "l0", term: "発端", weight: 1.2 },
  { layerSlug: "l0", term: "素地", weight: 1.1 },
  { layerSlug: "l0", term: "基底", weight: 1.2 },
  { layerSlug: "l0", term: "原初", weight: 1.4 },
  { layerSlug: "l0", term: "発生源", weight: 1.3 },
  { layerSlug: "l0", term: "芽生え", weight: 1.2 },
  { layerSlug: "l0", term: "原質", weight: 1.3 },
  { layerSlug: "l0", term: "根拠", weight: 1.1 },
  { layerSlug: "l0", term: "宇宙", weight: 1.0 },
  { layerSlug: "l0", term: "虚無", weight: 1.2 },
  { layerSlug: "l0", term: "無から有", weight: 1.5 },
  { layerSlug: "l0", term: "創生", weight: 1.4 },
  { layerSlug: "l0", term: "霊性", weight: 1.1 },
  { layerSlug: "l0", term: "本性", weight: 1.3 },
  { layerSlug: "l0", term: "始まり", weight: 1.2 },
  { layerSlug: "l0", term: "原点", weight: 1.3 },
  { layerSlug: "l0", term: "核心", weight: 1.2 },
  { layerSlug: "l0", term: "内在", weight: 1.3 },
  { layerSlug: "l0", term: "超越", weight: 1.2 },
  { layerSlug: "l0", term: "絶対", weight: 1.1 },
  { layerSlug: "l0", term: "普遍", weight: 1.1 },
  { layerSlug: "l0", term: "原理", weight: 1.2 },
  { layerSlug: "l0", term: "エネルギー", weight: 1.1 },
  { layerSlug: "l0", term: "ポテンシャル", weight: 1.2 },

  // ===== L1 可能性空間 =====
  { layerSlug: "l1", term: "可能性", weight: 1.5 },
  { layerSlug: "l1", term: "選択", weight: 1.4 },
  { layerSlug: "l1", term: "分岐", weight: 1.5 },
  { layerSlug: "l1", term: "仮説", weight: 1.4 },
  { layerSlug: "l1", term: "確率", weight: 1.3 },
  { layerSlug: "l1", term: "代替", weight: 1.2 },
  { layerSlug: "l1", term: "オプション", weight: 1.2 },
  { layerSlug: "l1", term: "選択肢", weight: 1.4 },
  { layerSlug: "l1", term: "シナリオ", weight: 1.3 },
  { layerSlug: "l1", term: "可能", weight: 1.3 },
  { layerSlug: "l1", term: "不確実", weight: 1.2 },
  { layerSlug: "l1", term: "偶然", weight: 1.2 },
  { layerSlug: "l1", term: "必然", weight: 1.1 },
  { layerSlug: "l1", term: "蓋然性", weight: 1.4 },
  { layerSlug: "l1", term: "潜在性", weight: 1.3 },
  { layerSlug: "l1", term: "多様性", weight: 1.2 },
  { layerSlug: "l1", term: "複数", weight: 1.1 },
  { layerSlug: "l1", term: "並列", weight: 1.2 },
  { layerSlug: "l1", term: "岐路", weight: 1.3 },
  { layerSlug: "l1", term: "転換点", weight: 1.3 },
  { layerSlug: "l1", term: "決断", weight: 1.2 },
  { layerSlug: "l1", term: "判断", weight: 1.1 },
  { layerSlug: "l1", term: "リスク", weight: 1.2 },
  { layerSlug: "l1", term: "見通し", weight: 1.1 },
  { layerSlug: "l1", term: "予測", weight: 1.2 },
  { layerSlug: "l1", term: "推測", weight: 1.1 },
  { layerSlug: "l1", term: "仮定", weight: 1.3 },
  { layerSlug: "l1", term: "条件", weight: 1.1 },
  { layerSlug: "l1", term: "前提", weight: 1.2 },
  { layerSlug: "l1", term: "未来", weight: 1.1 },
  { layerSlug: "l1", term: "将来", weight: 1.1 },
  { layerSlug: "l1", term: "展望", weight: 1.2 },
  { layerSlug: "l1", term: "潜在的", weight: 1.3 },
  { layerSlug: "l1", term: "仮想", weight: 1.2 },
  { layerSlug: "l1", term: "想定", weight: 1.2 },
  { layerSlug: "l1", term: "可変", weight: 1.1 },
  { layerSlug: "l1", term: "流動的", weight: 1.2 },
  { layerSlug: "l1", term: "不定", weight: 1.1 },
  { layerSlug: "l1", term: "余地", weight: 1.1 },
  { layerSlug: "l1", term: "自由度", weight: 1.2 },
  { layerSlug: "l1", term: "幅", weight: 1.0 },
  { layerSlug: "l1", term: "選べる", weight: 1.1 },
  { layerSlug: "l1", term: "分かれ道", weight: 1.2 },
  { layerSlug: "l1", term: "ランダム", weight: 1.1 },
  { layerSlug: "l1", term: "確率的", weight: 1.3 },

  // ===== L2 時間因果 =====
  { layerSlug: "l2", term: "原因", weight: 1.5 },
  { layerSlug: "l2", term: "結果", weight: 1.5 },
  { layerSlug: "l2", term: "プロセス", weight: 1.3 },
  { layerSlug: "l2", term: "時系列", weight: 1.4 },
  { layerSlug: "l2", term: "因果", weight: 1.5 },
  { layerSlug: "l2", term: "連鎖", weight: 1.3 },
  { layerSlug: "l2", term: "展開", weight: 1.2 },
  { layerSlug: "l2", term: "過程", weight: 1.3 },
  { layerSlug: "l2", term: "変化", weight: 1.2 },
  { layerSlug: "l2", term: "推移", weight: 1.3 },
  { layerSlug: "l2", term: "影響", weight: 1.3 },
  { layerSlug: "l2", term: "時間", weight: 1.1 },
  { layerSlug: "l2", term: "順序", weight: 1.2 },
  { layerSlug: "l2", term: "段階", weight: 1.2 },
  { layerSlug: "l2", term: "ステップ", weight: 1.2 },
  { layerSlug: "l2", term: "流れ", weight: 1.1 },
  { layerSlug: "l2", term: "継続", weight: 1.1 },
  { layerSlug: "l2", term: "発展", weight: 1.2 },
  { layerSlug: "l2", term: "進化", weight: 1.3 },
  { layerSlug: "l2", term: "進行", weight: 1.2 },
  { layerSlug: "l2", term: "促進", weight: 1.2 },
  { layerSlug: "l2", term: "阻害", weight: 1.2 },
  { layerSlug: "l2", term: "引き起こす", weight: 1.4 },
  { layerSlug: "l2", term: "もたらす", weight: 1.3 },
  { layerSlug: "l2", term: "起因", weight: 1.4 },
  { layerSlug: "l2", term: "誘発", weight: 1.3 },
  { layerSlug: "l2", term: "連動", weight: 1.2 },
  { layerSlug: "l2", term: "波及", weight: 1.3 },
  { layerSlug: "l2", term: "帰結", weight: 1.4 },
  { layerSlug: "l2", term: "遷移", weight: 1.3 },
  { layerSlug: "l2", term: "変遷", weight: 1.3 },
  { layerSlug: "l2", term: "歴史", weight: 1.1 },
  { layerSlug: "l2", term: "経緯", weight: 1.2 },
  { layerSlug: "l2", term: "背景", weight: 1.1 },
  { layerSlug: "l2", term: "前後", weight: 1.1 },
  { layerSlug: "l2", term: "循環", weight: 1.2 },
  { layerSlug: "l2", term: "反復", weight: 1.1 },
  { layerSlug: "l2", term: "蓄積", weight: 1.2 },
  { layerSlug: "l2", term: "収束", weight: 1.2 },
  { layerSlug: "l2", term: "分解", weight: 1.1 },
  { layerSlug: "l2", term: "合成", weight: 1.1 },
  { layerSlug: "l2", term: "相互作用", weight: 1.3 },
  { layerSlug: "l2", term: "フィードバック", weight: 1.3 },
  { layerSlug: "l2", term: "メカニズム", weight: 1.2 },
  { layerSlug: "l2", term: "ダイナミクス", weight: 1.3 },

  // ===== L3 主体心理 =====
  { layerSlug: "l3", term: "感情", weight: 1.5 },
  { layerSlug: "l3", term: "動機", weight: 1.5 },
  { layerSlug: "l3", term: "意図", weight: 1.4 },
  { layerSlug: "l3", term: "主観", weight: 1.4 },
  { layerSlug: "l3", term: "認知", weight: 1.3 },
  { layerSlug: "l3", term: "欲求", weight: 1.4 },
  { layerSlug: "l3", term: "心理", weight: 1.5 },
  { layerSlug: "l3", term: "意志", weight: 1.4 },
  { layerSlug: "l3", term: "感覚", weight: 1.3 },
  { layerSlug: "l3", term: "思考", weight: 1.3 },
  { layerSlug: "l3", term: "信念", weight: 1.3 },
  { layerSlug: "l3", term: "価値観", weight: 1.3 },
  { layerSlug: "l3", term: "自己", weight: 1.2 },
  { layerSlug: "l3", term: "内面", weight: 1.3 },
  { layerSlug: "l3", term: "経験", weight: 1.1 },
  { layerSlug: "l3", term: "記憶", weight: 1.2 },
  { layerSlug: "l3", term: "愛", weight: 1.3 },
  { layerSlug: "l3", term: "恐怖", weight: 1.3 },
  { layerSlug: "l3", term: "怒り", weight: 1.3 },
  { layerSlug: "l3", term: "喜び", weight: 1.3 },
  { layerSlug: "l3", term: "悲しみ", weight: 1.3 },
  { layerSlug: "l3", term: "不安", weight: 1.3 },
  { layerSlug: "l3", term: "希望", weight: 1.2 },
  { layerSlug: "l3", term: "絶望", weight: 1.3 },
  { layerSlug: "l3", term: "嫉妬", weight: 1.2 },
  { layerSlug: "l3", term: "誇り", weight: 1.2 },
  { layerSlug: "l3", term: "羞恥", weight: 1.2 },
  { layerSlug: "l3", term: "罪悪感", weight: 1.3 },
  { layerSlug: "l3", term: "共感", weight: 1.3 },
  { layerSlug: "l3", term: "同情", weight: 1.2 },
  { layerSlug: "l3", term: "愛着", weight: 1.3 },
  { layerSlug: "l3", term: "恨み", weight: 1.2 },
  { layerSlug: "l3", term: "欲望", weight: 1.4 },
  { layerSlug: "l3", term: "衝動", weight: 1.3 },
  { layerSlug: "l3", term: "本能", weight: 1.3 },
  { layerSlug: "l3", term: "意識", weight: 1.3 },
  { layerSlug: "l3", term: "無意識", weight: 1.3 },
  { layerSlug: "l3", term: "自我", weight: 1.3 },
  { layerSlug: "l3", term: "感受性", weight: 1.2 },
  { layerSlug: "l3", term: "情緒", weight: 1.3 },
  { layerSlug: "l3", term: "情動", weight: 1.3 },
  { layerSlug: "l3", term: "心", weight: 1.2 },
  { layerSlug: "l3", term: "精神", weight: 1.2 },
  { layerSlug: "l3", term: "魂", weight: 1.2 },
  { layerSlug: "l3", term: "望み", weight: 1.2 },
  { layerSlug: "l3", term: "夢", weight: 1.1 },
  { layerSlug: "l3", term: "渇望", weight: 1.3 },
  { layerSlug: "l3", term: "満足", weight: 1.2 },
  { layerSlug: "l3", term: "苦痛", weight: 1.2 },
  { layerSlug: "l3", term: "快楽", weight: 1.2 },
  { layerSlug: "l3", term: "葛藤", weight: 1.3 },
  { layerSlug: "l3", term: "迷い", weight: 1.2 },
  { layerSlug: "l3", term: "確信", weight: 1.2 },
  { layerSlug: "l3", term: "疑念", weight: 1.2 },
  { layerSlug: "l3", term: "自信", weight: 1.1 },
  { layerSlug: "l3", term: "恐れ", weight: 1.2 },
  { layerSlug: "l3", term: "期待", weight: 1.2 },
  { layerSlug: "l3", term: "執着", weight: 1.3 },
  { layerSlug: "l3", term: "解放", weight: 1.1 },
  { layerSlug: "l3", term: "感謝", weight: 1.1 },
  { layerSlug: "l3", term: "嫌悪", weight: 1.2 },

  // ===== L4 社会評価 =====
  { layerSlug: "l4", term: "評価", weight: 1.5 },
  { layerSlug: "l4", term: "規範", weight: 1.4 },
  { layerSlug: "l4", term: "批判", weight: 1.3 },
  { layerSlug: "l4", term: "称賛", weight: 1.3 },
  { layerSlug: "l4", term: "社会的", weight: 1.3 },
  { layerSlug: "l4", term: "価値判断", weight: 1.5 },
  { layerSlug: "l4", term: "評判", weight: 1.3 },
  { layerSlug: "l4", term: "道徳", weight: 1.4 },
  { layerSlug: "l4", term: "倫理", weight: 1.4 },
  { layerSlug: "l4", term: "善悪", weight: 1.4 },
  { layerSlug: "l4", term: "正義", weight: 1.4 },
  { layerSlug: "l4", term: "不正", weight: 1.3 },
  { layerSlug: "l4", term: "公正", weight: 1.4 },
  { layerSlug: "l4", term: "不公平", weight: 1.3 },
  { layerSlug: "l4", term: "差別", weight: 1.3 },
  { layerSlug: "l4", term: "偏見", weight: 1.3 },
  { layerSlug: "l4", term: "信頼", weight: 1.2 },
  { layerSlug: "l4", term: "裏切り", weight: 1.3 },
  { layerSlug: "l4", term: "名誉", weight: 1.3 },
  { layerSlug: "l4", term: "恥", weight: 1.2 },
  { layerSlug: "l4", term: "責任", weight: 1.3 },
  { layerSlug: "l4", term: "義務", weight: 1.3 },
  { layerSlug: "l4", term: "権利", weight: 1.3 },
  { layerSlug: "l4", term: "文化", weight: 1.1 },
  { layerSlug: "l4", term: "慣習", weight: 1.2 },
  { layerSlug: "l4", term: "タブー", weight: 1.2 },
  { layerSlug: "l4", term: "スティグマ", weight: 1.3 },
  { layerSlug: "l4", term: "名声", weight: 1.2 },
  { layerSlug: "l4", term: "威信", weight: 1.2 },
  { layerSlug: "l4", term: "ステータス", weight: 1.2 },
  { layerSlug: "l4", term: "地位", weight: 1.2 },
  { layerSlug: "l4", term: "階層", weight: 1.2 },
  { layerSlug: "l4", term: "支配", weight: 1.2 },
  { layerSlug: "l4", term: "権力", weight: 1.2 },
  { layerSlug: "l4", term: "影響力", weight: 1.2 },
  { layerSlug: "l4", term: "世論", weight: 1.3 },
  { layerSlug: "l4", term: "合意", weight: 1.2 },
  { layerSlug: "l4", term: "社会規範", weight: 1.4 },
  { layerSlug: "l4", term: "ルール", weight: 1.1 },
  { layerSlug: "l4", term: "規則", weight: 1.2 },
  { layerSlug: "l4", term: "マナー", weight: 1.1 },
  { layerSlug: "l4", term: "エチケット", weight: 1.1 },
  { layerSlug: "l4", term: "体裁", weight: 1.1 },
  { layerSlug: "l4", term: "面子", weight: 1.2 },
  { layerSlug: "l4", term: "ブランド", weight: 1.1 },
  { layerSlug: "l4", term: "イメージ", weight: 1.1 },
  { layerSlug: "l4", term: "印象", weight: 1.1 },
  { layerSlug: "l4", term: "好感", weight: 1.1 },
  { layerSlug: "l4", term: "非難", weight: 1.3 },
  { layerSlug: "l4", term: "賞賛", weight: 1.2 },
  { layerSlug: "l4", term: "承認", weight: 1.2 },
  { layerSlug: "l4", term: "排除", weight: 1.2 },
  { layerSlug: "l4", term: "包摂", weight: 1.2 },
  { layerSlug: "l4", term: "連帯", weight: 1.2 },
  { layerSlug: "l4", term: "共同体", weight: 1.2 },

  // ===== L5 制度形式 =====
  { layerSlug: "l5", term: "制度", weight: 1.5 },
  { layerSlug: "l5", term: "法律", weight: 1.5 },
  { layerSlug: "l5", term: "手続き", weight: 1.4 },
  { layerSlug: "l5", term: "規定", weight: 1.4 },
  { layerSlug: "l5", term: "形式", weight: 1.3 },
  { layerSlug: "l5", term: "条文", weight: 1.4 },
  { layerSlug: "l5", term: "制裁", weight: 1.3 },
  { layerSlug: "l5", term: "契約", weight: 1.4 },
  { layerSlug: "l5", term: "条約", weight: 1.4 },
  { layerSlug: "l5", term: "憲法", weight: 1.5 },
  { layerSlug: "l5", term: "法令", weight: 1.4 },
  { layerSlug: "l5", term: "条例", weight: 1.3 },
  { layerSlug: "l5", term: "規制", weight: 1.3 },
  { layerSlug: "l5", term: "認可", weight: 1.3 },
  { layerSlug: "l5", term: "許可", weight: 1.2 },
  { layerSlug: "l5", term: "禁止", weight: 1.3 },
  { layerSlug: "l5", term: "罰則", weight: 1.3 },
  { layerSlug: "l5", term: "刑罰", weight: 1.4 },
  { layerSlug: "l5", term: "訴訟", weight: 1.3 },
  { layerSlug: "l5", term: "裁判", weight: 1.4 },
  { layerSlug: "l5", term: "判決", weight: 1.4 },
  { layerSlug: "l5", term: "行政", weight: 1.3 },
  { layerSlug: "l5", term: "官僚", weight: 1.2 },
  { layerSlug: "l5", term: "政府", weight: 1.2 },
  { layerSlug: "l5", term: "政策", weight: 1.3 },
  { layerSlug: "l5", term: "立法", weight: 1.4 },
  { layerSlug: "l5", term: "司法", weight: 1.4 },
  { layerSlug: "l5", term: "行政機関", weight: 1.3 },
  { layerSlug: "l5", term: "組織", weight: 1.1 },
  { layerSlug: "l5", term: "官僚制", weight: 1.3 },
  { layerSlug: "l5", term: "フォーマル", weight: 1.2 },
  { layerSlug: "l5", term: "書面", weight: 1.2 },
  { layerSlug: "l5", term: "公文書", weight: 1.3 },
  { layerSlug: "l5", term: "署名", weight: 1.2 },
  { layerSlug: "l5", term: "認証", weight: 1.2 },
  { layerSlug: "l5", term: "登録", weight: 1.2 },
  { layerSlug: "l5", term: "届出", weight: 1.2 },
  { layerSlug: "l5", term: "申請", weight: 1.2 },
  { layerSlug: "l5", term: "審査", weight: 1.3 },
  { layerSlug: "l5", term: "監査", weight: 1.3 },
  { layerSlug: "l5", term: "コンプライアンス", weight: 1.4 },
  { layerSlug: "l5", term: "ガバナンス", weight: 1.3 },
  { layerSlug: "l5", term: "プロトコル", weight: 1.3 },
  { layerSlug: "l5", term: "標準", weight: 1.2 },
  { layerSlug: "l5", term: "基準", weight: 1.2 },
  { layerSlug: "l5", term: "指針", weight: 1.2 },
  { layerSlug: "l5", term: "ガイドライン", weight: 1.2 },
  { layerSlug: "l5", term: "マニュアル", weight: 1.1 },
  { layerSlug: "l5", term: "規約", weight: 1.3 },
  { layerSlug: "l5", term: "定款", weight: 1.3 },
  { layerSlug: "l5", term: "議事録", weight: 1.2 },
  { layerSlug: "l5", term: "権限", weight: 1.2 },
  { layerSlug: "l5", term: "管轄", weight: 1.2 },
  { layerSlug: "l5", term: "管理", weight: 1.1 },
  { layerSlug: "l5", term: "統制", weight: 1.2 },

  // ===== 否定語 =====
  { layerSlug: "l0", term: "消滅", weight: 1.2, isNegation: true },
  { layerSlug: "l0", term: "無", weight: 1.1, isNegation: true },
  { layerSlug: "l1", term: "不可能", weight: 1.3, isNegation: true },
  { layerSlug: "l1", term: "閉塞", weight: 1.2, isNegation: true },
  { layerSlug: "l2", term: "停止", weight: 1.2, isNegation: true },
  { layerSlug: "l3", term: "無関心", weight: 1.2, isNegation: true },
  { layerSlug: "l4", term: "無価値", weight: 1.2, isNegation: true },
  { layerSlug: "l5", term: "違法", weight: 1.3, isNegation: true },
  { layerSlug: "l5", term: "無効", weight: 1.2, isNegation: true },
];

const concepts = [
  {
    slug: "sekinin", titleJa: "責任", summary: "行為の帰属と義務の概念。行動の結果に対する説明責任と応答可能性。", tags: ["倫理", "社会", "法律"],
    entries: {
      l0: "責任とは行為が存在として帰属する根源的な関係性である。行為の発生と主体の結びつきが責任の発生位相を形成する。存在することそのものが、すでに応答可能性を含んでいる。",
      l1: "責任を問うかどうか、誰に問うか、どの程度問うかという複数の選択肢が存在する。免責・軽減・全責任という分岐があり、当事者の合意によって帰着が変わる可能性がある。",
      l2: "行為→結果→帰属→制裁という時間的因果連鎖の中に責任は位置づけられる。原因行為が先行し、結果が後続し、帰属の評価が加わることで責任が確定する。",
      l3: "責任感・罪悪感・義務感という主観的感情を伴う。責任を感じるかどうかは主体の認知と感情に依存する。内面的な応答可能性の感覚が責任の心理的基盤となる。",
      l4: "社会的に責任ある行動が称賛され、無責任は批判される。道徳的・法的責任への社会評価が存在し、集団の規範が個人の責任のあり方を規定する。",
      l5: "法的責任は刑法・民法・行政法で制度化されている。賠償・処罰・回復という形式的手続きが制度として整備され、責任の範囲と対応が規範的に確定される。",
    },
  },
  {
    slug: "jiyu", titleJa: "自由", summary: "制約からの解放と自律的意思決定の能力。", tags: ["哲学", "政治", "人権"],
    entries: {
      l0: "自由とは存在が自らの根拠によって在ることができる根源的状態である。束縛からの解放ではなく、自己原因性としての自由が本質的位相を形成する。",
      l1: "自由は複数の選択肢が開かれている状態を意味する。どの可能性も選択できるという開放性が自由の論理的条件であり、閉鎖系には自由は成立しない。",
      l2: "自由の拡大は歴史的プロセスを経て達成されてきた。抑圧→抵抗→解放という時間的因果連鎖が自由の歴史を形成し、次の世代に引き継がれる。",
      l3: "自由の感覚は主観的体験として現れる。束縛されていないという内面的確信、自己決定の感覚、選択する喜びが自由の心理的現実を構成する。",
      l4: "自由は社会的文脈において評価される。他者の自由との調整が求められ、「ある人の自由が他者の自由を侵害しない範囲」という規範が社会的に形成される。",
      l5: "自由は憲法・人権法・国際条約によって制度的に保護される。表現の自由・移動の自由・信教の自由など、形式的権利として法的に規定されている。",
    },
  },
  {
    slug: "seigi", titleJa: "正義", summary: "公正・公平・応報に関する規範的概念。", tags: ["哲学", "倫理", "法律"],
    entries: {
      l0: "正義とは存在の秩序における正しさの根源的現れである。あるべき姿と現実の乖離を感知する直観が正義感の発生位相を形成する。",
      l1: "正義の実現方法には複数の選択肢がある。応報的正義・修復的正義・分配的正義など、どの正義観を採るかという根本的分岐が存在する。",
      l2: "不正→抵抗→正義実現という因果プロセスが社会的変革を生む。歴史的に正義の定義は変化し、過去の不正義への対応が現在の正義の課題となる。",
      l3: "正義感は深い感情的確信を伴う。不公平への怒り、被害者への共感、秩序回復への渇望が正義追求の心理的動力となる。",
      l4: "正義は社会的に構築される評価基準である。何が正義かは文化・時代・共同体によって異なり、社会的合意を通じて規範として確立される。",
      l5: "正義は司法制度・法律・国際法によって形式化される。裁判所・検察・弁護制度が正義実現の制度的装置として機能する。",
    },
  },
  {
    slug: "ai", titleJa: "愛", summary: "深い感情的つながりと他者への配慮。", tags: ["感情", "関係", "哲学"],
    entries: {
      l0: "愛とは生命存在の根源的な引力であり、他者への開放性の根本的位相である。存在そのものの自己超越性が愛の発生基盤を形成する。",
      l1: "愛の形態は多様で、誰を・どのように・どの程度愛するかという無数の選択肢がある。ロマンティックな愛・友愛・親子愛・普遍的愛など複数の様態が並存する。",
      l2: "愛は出会い→惹きつけ→深化→変容というプロセスを経る。時間の中で育まれ、試練を経て変質し、喪失によって新たな意味を獲得する。",
      l3: "愛は人間の最も強烈な感情体験の一つである。愛する者への献身、喜びと苦しみの交錯、一体感と喪失への恐怖が愛の心理的複雑さを形成する。",
      l4: "愛は社会的規範によって形作られる。どのような愛が認められ、どのような愛が禁じられるかは文化・時代・宗教によって異なる社会評価の対象となる。",
      l5: "愛は婚姻制度・家族法・養子縁組法など多くの法的制度と接続する。愛に基づく関係が法的権利義務を生み、制度的保護の対象となる。",
    },
  },
  {
    slug: "kenryoku", titleJa: "権力", summary: "他者に影響を与え従わせる能力と構造。", tags: ["政治", "社会", "組織"],
    entries: {
      l0: "権力とは関係性の中に潜在する非対称性の根源的現れである。強制する能力の発生が権力の位相を形成し、存在の差異から権力は生まれる。",
      l1: "権力は行使するか否か、誰に対して、どの程度行使するかという選択の空間を持つ。権力の分散・集中・移譲という様々なシナリオが可能である。",
      l2: "権力は獲得→維持→喪失というサイクルを経る。権力の空白が新たな権力争いを生み、歴史は権力移行の連鎖として描くことができる。",
      l3: "権力欲は人間の根源的動機の一つである。支配への欲求、服従への恐怖、承認への渇望が権力関係の心理的基盤を形成する。",
      l4: "権力の正当性は社会的評価によって決まる。何が正当な権力かという問いは常に社会的争点であり、権力の濫用は道徳的批判の対象となる。",
      l5: "権力は法的権限・制度的地位・憲法秩序として形式化される。三権分立・民主的統制・法の支配が権力を制度的に規律する原理となる。",
    },
  },
  {
    slug: "shinjitsu", titleJa: "真実", summary: "現実に対応する命題の性質と認識論的問題。", tags: ["哲学", "認識論", "科学"],
    entries: {
      l0: "真実とは存在と認識の根源的対応関係である。あるものがあるがままに現れる位相が真実の発生基盤であり、隠蔽と開示の緊張の中に真実はある。",
      l1: "真実へのアプローチは複数ある。対応説・整合説・プラグマティズムなど、何を真実とするかという根本的選択が認識論的分岐を生む。",
      l2: "真実の探求は仮説→検証→修正というプロセスを経る。科学的方法は時間的連鎖を通じて真実に漸近し、誤りの排除によって知識が蓄積される。",
      l3: "真実を知りたいという欲求と、知りたくないという回避が葛藤する。確信・疑念・信念が真実認識の心理的側面を形成し、認知バイアスが真実把握を歪める。",
      l4: "社会的真実は集合的合意によって構築される。何を真実とするかは権力と無関係ではなく、公式な真実と非公式な真実の乖離が社会的緊張を生む。",
      l5: "法的真実は証拠規則・証明基準によって制度的に確定される。「合理的な疑いを超える証明」など形式的基準が司法の場での真実認定を規律する。",
    },
  },
  {
    slug: "jikan", titleJa: "時間", summary: "変化の尺度であり存在の様式。過去・現在・未来の構造。", tags: ["哲学", "物理", "存在論"],
    entries: {
      l0: "時間とは存在の変化可能性の根源的位相である。無時間的な永遠と時間的な生成の対立が時間概念の発生基盤を形成する。",
      l1: "時間の使い方は選択の問題である。限られた時間をどこに配分するか、過去・現在・未来のどこに重心を置くかという根本的選択が人生を形作る。",
      l2: "時間は因果の媒体である。原因は結果に先行し、時間の矢は一方向に進む。時間なしに因果関係は成立せず、歴史は時間的連鎖として構成される。",
      l3: "時間体験は主観的である。時間の主観的速度・過去への郷愁・未来への不安・現在への没入が時間の心理的現実を形成する。",
      l4: "時間管理は社会的規範となっている。時間厳守・効率・生産性への社会的評価が、時間との関係の文化的規範を形成している。",
      l5: "時間は法的文脈で精密に定義される。時効・締め切り・任期・契約期間など、時間の法的意味が権利義務の発生・消滅を決定する。",
    },
  },
  {
    slug: "shizen", titleJa: "自然", summary: "人為を超えた存在の総体と生態系。", tags: ["環境", "哲学", "科学"],
    entries: {
      l0: "自然とは人為的に構成されていない存在の根源的様相である。生命の自発的生成、物質の運動、宇宙の秩序が自然の発生位相を形成する。",
      l1: "自然への関わり方には複数の選択肢がある。支配するか共生するか、開発するか保護するかという根本的分岐が環境政策と個人の選択に現れる。",
      l2: "自然は生態系という複雑な因果連鎖によって成立する。食物連鎖・物質循環・エネルギーフローが相互に連動し、一部の変化が全体に波及する。",
      l3: "自然は人間に深い感情的経験をもたらす。畏敬・安らぎ・恐怖・美しさへの感動が自然との心理的関係を形成する。",
      l4: "自然をどう扱うかは社会的・倫理的問題である。環境保護・持続可能性・世代間公正が社会的規範として形成され、自然破壊は批判の対象となる。",
      l5: "自然は環境法・自然保護法・国際環境条約によって法的に保護される。環境影響評価・排出規制・保護区指定が制度的に自然を守る仕組みを形成する。",
    },
  },
  {
    slug: "kotoba", titleJa: "言葉", summary: "意味を媒介する記号系。コミュニケーションと思考の道具。", tags: ["言語", "哲学", "コミュニケーション"],
    entries: {
      l0: "言葉とは存在が自己表現する根源的媒体である。意味の生成と伝達が可能になる言語的場の成立が、言葉の発生位相を形成する。",
      l1: "言葉の選択は常に可能性の選択である。何を言い、何を言わないか、どう表現するかという選択が、意味の生成と関係の構築に影響する。",
      l2: "言葉は発話→伝達→解釈→応答という時間的連鎖を生む。誤解・訂正・理解深化というプロセスを経て意味が共有され、対話が展開する。",
      l3: "言葉は感情を表現し、また感情を生み出す。言葉によって傷つき、言葉によって癒される。内面の経験を言語化する行為は自己認識を変容させる。",
      l4: "言葉は社会的権力と深く結びついている。何が言えるか、何が禁じられるかは社会的規範によって規律され、言語的差別・ヘイトスピーチは批判の対象となる。",
      l5: "言論の自由は憲法で保護され、名誉毀損・侮辱・脅迫は法的に規制される。著作権・商標権・プライバシー権が言語表現の法的枠組みを形成する。",
    },
  },
  {
    slug: "kanemochi", titleJa: "富", summary: "経済的豊かさと資源の集積。分配と格差の問題。", tags: ["経済", "社会", "倫理"],
    entries: {
      l0: "富とは資源・エネルギー・価値の根源的蓄積状態である。何かを生産・獲得する能力の潜在性が富の発生位相を形成する。",
      l1: "富の獲得・分配・使用には選択肢がある。投資か消費か、独占か分配か、蓄積か循環かという選択が個人と社会の富の様態を決定する。",
      l2: "富は生産→流通→消費→再生産という経済的連鎖の中で生成される。資本の蓄積と再投資が富の増大をもたらし、経済危機は蓄積の連鎖を断ち切る。",
      l3: "富への欲求と富の喪失への恐怖が人間行動を動機づける。安心感・優越感・罪悪感・飢餓感が富に関する心理的複雑さを形成する。",
      l4: "富の分配は社会的正義の問題である。格差拡大は批判され、富裕層への課税・再分配政策が道徳的議論の対象となる。豊かさと貧困の共存が社会評価の焦点となる。",
      l5: "富は財産権・相続法・税法・金融規制によって法的に規律される。所得税・資産税・贈与税が富の移転と蓄積を制度的に規律する。",
    },
  },
  {
    slug: "sensou", titleJa: "戦争", summary: "集団間の組織的暴力とその構造・原因・帰結。", tags: ["政治", "歴史", "倫理"],
    entries: {
      l0: "戦争とは集団的暴力が発現する根源的位相である。対立・恐怖・資源への欲求が暴力的衝突の潜在性を生み出し、臨界点で戦争が発生する。",
      l1: "戦争を始めるか否か、どの手段を用いるか、いつ終わらせるかという選択肢が常に存在する。外交・抑止・降伏・徹底抗戦という分岐が戦争の展開を決定する。",
      l2: "戦争は原因→開戦→戦闘→終戦→和平という時間的連鎖を持つ。一つの戦争が次の戦争の原因となり、歴史は戦争の連鎖として記述できる側面がある。",
      l3: "戦争は恐怖・怒り・愛国心・憎悪・英雄主義など強烈な感情を生み出す。戦闘員のトラウマ、喪失の悲しみ、勝利の高揚が戦争の心理的側面を形成する。",
      l4: "戦争の評価は複雑である。「正戦論」が示すように、何が正当な戦争かは倫理的議論の的であり、戦争犯罪・民間人保護・戦後補償が社会的規範として形成されてきた。",
      l5: "戦争は国際法・ジュネーブ条約・国連憲章によって規律される。宣戦布告・捕虜扱い・民間人保護・核兵器禁止などが法的に規定されている。",
    },
  },
  {
    slug: "kyouiku", titleJa: "教育", summary: "知識・技能・価値観の伝達と人間形成のプロセス。", tags: ["社会", "文化", "発達"],
    entries: {
      l0: "教育とは人間の可能性を顕現させる根源的プロセスである。潜在する能力・知性・人間性が教育という場において発現する位相を形成する。",
      l1: "教育には何を教えるか、どう教えるかという根本的選択がある。知識重視か能力重視か、画一的か個別的か、競争か協働かという分岐が教育の形を決定する。",
      l2: "教育は学習→内化→応用→創造という認知的プロセスを生む。教師と学習者の相互作用が知識の移転と変容をもたらし、世代を超えて文化が伝達される。",
      l3: "学ぶ喜び・知への好奇心・達成感・挫折感が教育の心理的側面を形成する。教師への信頼・友人との競争・承認への欲求が学習動機を生み出す。",
      l4: "教育は社会的評価と密接に結びついている。学歴・資格・偏差値が社会的地位と連動し、教育の機会格差が社会問題として批判される。",
      l5: "教育権は憲法で保障され、学校教育法・教育基本法が制度を規律する。義務教育・教員免許・学習指導要領が教育の形式的枠組みを法的に定める。",
    },
  },
  {
    slug: "heiwa", titleJa: "平和", summary: "暴力の不在と積極的な共生状態。", tags: ["政治", "倫理", "社会"],
    entries: {
      l0: "平和とは存在が暴力的破壊なしに在り続けられる根源的状態である。生命の持続可能性と関係の調和が平和の発生位相を形成する。",
      l1: "平和は維持するための選択を常に求める。軍備か軍縮か、対話か強硬姿勢か、関与か孤立かという選択が平和の可能性を左右する。",
      l2: "平和は交渉→合意→信頼構築→制度化という時間的プロセスを必要とする。歴史的和解は過去の暴力の清算を経て初めて深い平和が可能となる。",
      l3: "平和への希求は人間の根源的感情に根ざす。暴力への恐怖・安全への欲求・調和への渇望が平和の心理的基盤を形成する。",
      l4: "平和は最高の社会的価値の一つとして評価される。平和を乱す行為は強く批判され、平和への貢献は称賛される社会的規範が形成されてきた。",
      l5: "平和は国連憲章・平和条約・安全保障体制によって制度的に支えられる。集団安全保障・軍備管理条約・紛争調停機関が平和の法的・制度的基盤を形成する。",
    },
  },
  {
    slug: "gijutsu", titleJa: "技術", summary: "人間の目的を達成するための体系的な手段と知識。", tags: ["科学", "イノベーション", "社会"],
    entries: {
      l0: "技術とは人間の能力を延長・増幅する根源的な媒体である。道具の発明が人間と自然の関係を変え、新たな可能性の位相を創出する。",
      l1: "技術の開発・採用・廃棄には選択肢がある。どの技術を優先するか、技術と人間のどちらを中心に置くかという根本的分岐が技術社会の形を決定する。",
      l2: "技術は発明→普及→最適化→陳腐化→次世代技術という時間的連鎖を経る。技術革新が経済・社会・文化を変容させ、新たな技術的問題を生み出す。",
      l3: "技術への好奇心・革新の喜び・技術への依存・テクノフォビアが技術の心理的側面を形成する。創造性の充足と自律性の喪失が技術との関係を複雑にする。",
      l4: "技術の社会的評価は急速に変化する。イノベーションは称賛され、技術的失業・プライバシー侵害・軍事転用は批判される社会的規範が形成されている。",
      l5: "技術は特許法・著作権法・製造物責任法・AI規制法によって法的に規律される。技術標準・安全基準・倫理ガイドラインが制度的枠組みを形成する。",
    },
  },
  {
    slug: "byoki", titleJa: "病気", summary: "身体・精神の機能不全と医療・ケアの問題。", tags: ["医療", "身体", "社会"],
    entries: {
      l0: "病気とは生命の秩序が根源的に乱れた状態である。健康という本来の在り方からの逸脱が病気の発生位相を形成し、生命の脆弱性を顕にする。",
      l1: "病気への対応には選択肢がある。治療するか緩和するか、西洋医学か代替医療か、入院か在宅かという選択が患者と医療者の間で常に問われる。",
      l2: "病気は原因→症状→診断→治療→回復（または悪化）という時間的プロセスを経る。感染の連鎖・慢性化・再発が病気の時間的複雑さを形成する。",
      l3: "病気は恐怖・否認・怒り・悲しみ・受容という感情的プロセスを伴う。慢性疾患の心理的負担、死への恐怖、ケアする者の感情が病気の心理的側面を形成する。",
      l4: "病気は社会的スティグマと結びつくことがある。精神疾患・感染症・依存症への偏見が社会的評価を歪め、患者の社会的排除を生む場合がある。",
      l5: "医療は医師法・薬事法・医療保険制度・患者権利法によって規律される。インフォームドコンセント・個人情報保護・医療倫理が法的・制度的枠組みを形成する。",
    },
  },
  {
    slug: "kazoku", titleJa: "家族", summary: "血縁・婚姻・養育関係で結ばれた最小社会単位。", tags: ["社会", "関係", "文化"],
    entries: {
      l0: "家族とは生命の連続性と親密性が根源的に発現する場である。血縁・出産・養育という生物的基盤の上に、深い情緒的結びつきが形成される。",
      l1: "家族の形態は多様な選択肢を持つ。核家族・拡大家族・シングル親・同性カップル・里親など、家族の定義自体が可変的な選択肢の空間にある。",
      l2: "家族は出会い→結婚→子育て→老い→別れというライフサイクルの連鎖を持つ。各段階が次の段階に影響し、家族の歴史が世代を超えて連続する。",
      l3: "家族は愛・安心・依存・葛藤・競争が凝縮した感情的場である。愛着形成・アイデンティティ発達・心理的安全の基盤であり、傷つきの場にもなりうる。",
      l4: "家族のあり方は社会的規範によって規律される。「正常な家族」の定義は文化・時代によって変化し、家族規範からの逸脱が社会的批判の対象となる。",
      l5: "家族は民法・家族法・相続法・育児介護法によって法的に規律される。婚姻・離婚・親権・養子縁組・相続が法的権利義務として制度化されている。",
    },
  },
  {
    slug: "shigoto", titleJa: "仕事", summary: "価値を生み出す活動と労働の意味・構造。", tags: ["経済", "社会", "心理"],
    entries: {
      l0: "仕事とは人間が自己の能力を世界に発現させる根源的な活動である。創造・変革・貢献という行為を通じて、人間存在が世界に痕跡を刻む位相を形成する。",
      l1: "どの仕事を選ぶか、どう働くか、いつ辞めるかという選択が常に問われる。キャリアパス・起業か就職か・専門化か汎用化かという分岐が職業人生を形作る。",
      l2: "仕事は準備→実行→評価→改善という反復的プロセスを持つ。スキルの蓄積・経験からの学習・組織の中での信頼構築が時間的連鎖として展開する。",
      l3: "仕事への意欲・やりがい・燃え尽き・達成感が仕事の心理的側面を形成する。自己効力感・承認欲求・自律性への欲求が労働動機の心理的基盤となる。",
      l4: "仕事の価値は社会的評価によって大きく規定される。職業威信・収入への評価・社会貢献度への評価が仕事の社会的位置づけを決定する。",
      l5: "労働は労働基準法・雇用契約・労働組合法・社会保険制度によって法的に規律される。賃金・労働時間・安全衛生・解雇規制が制度的に労働を保護する。",
    },
  },
  {
    slug: "kioku", titleJa: "記憶", summary: "過去の経験を保持し現在に影響させる認知機能。", tags: ["心理", "認知", "哲学"],
    entries: {
      l0: "記憶とは過去の経験が現在において潜在的に存在し続ける根源的様式である。存在が時間を超えて持続する可能性の位相が記憶の発生基盤を形成する。",
      l1: "何を記憶し何を忘れるかという選択は部分的に意識的に行われる。想起・抑圧・改竄・美化という記憶操作の選択肢が記憶の多様な様態を生み出す。",
      l2: "記憶は符号化→保持→想起という時間的プロセスを経る。時間の経過による忘却・再学習による強化・感情的体験による記憶強化が記憶の時間的変化を形成する。",
      l3: "記憶は感情と深く結びついている。感情的記憶の強さ、郷愁・後悔・トラウマが記憶の心理的複雑さを形成し、記憶は現在の感情状態を規定する。",
      l4: "集合的記憶は社会的アイデンティティと規範を形成する。歴史認識・戦争記憶・文化的伝統が社会的評価の対象となり、記憶の政治が権力と結びつく。",
      l5: "記録の保存・文書管理・個人情報保護・忘れられる権利が法的に規律される。デジタルアーカイブ・公文書管理法が制度的に記憶の保存と消去を規定する。",
    },
  },
  {
    slug: "shindou", titleJa: "信頼", summary: "他者の行為への期待と脆弱性の受け入れ。", tags: ["社会", "心理", "倫理"],
    entries: {
      l0: "信頼とは他者に対して自己の脆弱性を開く根源的な存在様式である。関係の可能性が信頼によって生まれ、信頼なしには共同的存在は成立しない。",
      l1: "信頼するかしないか、誰を信頼するか、どの程度信頼するかという選択が関係を形成する。盲目的信頼・条件付き信頼・不信という分岐が社会関係の多様性を生む。",
      l2: "信頼は小さな約束の履行→信用の蓄積→深い信頼という時間的プロセスを経て築かれる。裏切りによって信頼は崩壊し、再構築には長い時間が必要となる。",
      l3: "信頼は安心感・開放性・脆弱性の受け入れを伴う感情状態である。裏切られた時の痛み、信頼回復への希望が信頼の心理的複雑さを形成する。",
      l4: "信頼は社会的資本として機能する。高信頼社会では協力が促進され取引コストが低下する。信頼の欠如は社会的分断と非効率をもたらす。",
      l5: "信頼は契約・保証・資格制度・規制・認証機関によって制度的に補完される。法的強制力が信頼の不在を補い、制度的信頼が個人的信頼を代替する。",
    },
  },
  {
    slug: "doki", titleJa: "動機", summary: "行動を引き起こす内的要因と心理的駆動力。", tags: ["心理", "行動", "哲学"],
    entries: {
      l0: "動機は行動を発生させる根源的エネルギーの位相にある。欲求・衝動・意志が動機の生成位相を形成し、行動の潜在性として存在する。",
      l1: "どの動機に従って行動するかという選択が生じる。複数の動機が競合し、優先順位の分岐が発生する。外発的動機か内発的動機かという選択が行動の質を決定する。",
      l2: "欲求発生→動機形成→行動→目標達成という因果連鎖。動機が原因となり、行動と結果が後続する。動機の変化が行動パターンの変化をもたらす。",
      l3: "動機は本質的に主観的・心理的である。欲求・感情・価値観が動機の心理的基盤を形成する。マズローの欲求階層のように、動機は層を成している。",
      l4: "純粋な動機は称賛され、不純な動機（私利私欲・計算高さ）は批判される。動機の透明性と真摯さが社会的評価の基準となる。",
      l5: "法的文脈では犯罪の動機が量刑に影響する。故意・過失・計画性が法的判断の要素となり、制度的に動機の認定手続きが存在する。",
    },
  },
  {
    slug: "mokuhyo", titleJa: "目標", summary: "達成を目指す具体的な状態と方向性。", tags: ["計画", "行動", "心理"],
    entries: {
      l0: "目標とは未来の理想状態が現在において潜在的に存在する位相である。目標設定が存在の方向性を生み、目的のある生の可能性を開く。",
      l1: "どの目標を選ぶか、複数の目標の中から優先順位をつける選択が必要となる。達成・断念・修正という分岐がある。短期目標か長期目標かの選択も重要である。",
      l2: "目標設定→計画→実行→達成・未達という時間的プロセスが展開する。各ステップが因果的に連鎖し、障害の克服が次の行動を規定する。",
      l3: "目標への執着・達成感・挫折感・諦めという感情が伴う。目標は主体の意図と認知によって形成され、自己効力感が目標達成に深く影響する。",
      l4: "高い目標設定は社会的に称賛される。目標達成者は評価され、失敗者への評価は文脈による。社会的圧力が目標の内容と水準を規定する場合がある。",
      l5: "KPI・OKR・契約目標など制度的な目標設定フレームワークが組織管理に使われる。法的拘束力を持つ目標もあり、業績評価制度が目標を形式化する。",
    },
  },
  {
    slug: "kachi", titleJa: "価値", summary: "重要性・有用性・意義の概念と評価の基準。", tags: ["哲学", "経済", "倫理"],
    entries: {
      l0: "価値とは存在の重要性・意義が顕在化する根源的位相である。無意味な存在から意味ある存在への転換点に価値の発生がある。",
      l1: "何に価値を見出すか、複数の価値観の中から選択する。交換するかしないかという価値判断の分岐。使用価値・交換価値・感情的価値の優先順位が問われる。",
      l2: "生産→流通→消費という価値の時間的連鎖。使用価値から交換価値への転換プロセスが展開し、希少性と需要の変化が価値の時間的変動を生む。",
      l3: "価値を感じる・感じないという主観的体験。美的価値・実用的価値への個人的感受性が異なる。内在的価値と外在的価値の違いが価値論の核心をなす。",
      l4: "社会的に高い価値を持つとされるものが評価される。文化的価値判断・市場価値の社会的形成が行われ、価値観の衝突が社会的緊張を生む。",
      l5: "価格制度・知的財産権・文化財指定など価値を制度的に確定・保護するシステムが存在する。会計基準・評価規制が価値の形式的認定を行う。",
    },
  },
  {
    slug: "kachi-make", titleJa: "勝ち負け", summary: "競争における優劣の判定と勝敗の意味。", tags: ["競争", "スポーツ", "心理"],
    entries: {
      l0: "勝ち負けは差異の発生・優劣の生成という根源的位相にある。競争の場が成立した瞬間に勝敗の可能性が生まれ、二項対立の構造が生成される。",
      l1: "勝つための戦略・戦術の選択が存在する。リスク取りか安全策か、短期戦か長期戦か、協力か単独かという複数の選択肢の分岐がある。",
      l2: "競争開始→プロセス→判定→勝敗確定という時間的因果連鎖。先行する行為が後続の結果を規定し、逆転・形勢逆転という時間的ドラマが展開する。",
      l3: "勝利の喜び・敗北の悔しさという強烈な感情体験。勝ちたいという欲求が主体を動かす心理的動力となり、勝敗が自己評価に深く影響する。",
      l4: "勝者は称賛・尊敬され、敗者は同情・軽蔑される場合がある。勝ち負けへの社会的評価と意味付けが存在し、スポーツマンシップが社会規範として機能する。",
      l5: "スポーツルール・審判制度・表彰制度など勝敗を制度的に確定する形式的システムが存在する。ドーピング規制・不正行為の法的制裁が競争の公正を守る。",
    },
  },
  {
    slug: "doteki-sesei", titleJa: "動的生成", summary: "時間とともに変化し生成するプロセスと複雑系。", tags: ["プロセス", "複雑系", "哲学"],
    entries: {
      l0: "動的生成とは存在が絶えず生成・変化・消滅する根源的位相である。静止した存在ではなく流動する過程そのものが実在の本質的様態を形成する。",
      l1: "どの方向に生成が進むか、複数の可能性が開かれている。分岐点で異なる生成パスが選ばれ、初期条件の微小な差異が大きな分岐をもたらす。",
      l2: "初期状態→変化プロセス→新しい状態という時間的展開。各段階が次の段階の原因となる連鎖が展開し、非線形的なダイナミクスが複雑なパターンを生む。",
      l3: "変化に対する期待・不安・興奮という感情。変化を意図するか流れに任せるかという主体的選択が動的生成への関与の様式を決定する。",
      l4: "イノベーションとしての動的生成は高く評価される。変化への適応力が社会的に評価され、硬直化した組織や制度は批判の対象となる。",
      l5: "プロセス管理・品質管理・アジャイル手法など動的生成を制度化するフレームワークが存在する。変化管理のガイドラインが組織の動的適応を規律する。",
    },
  },
  {
    slug: "ningen-mi", titleJa: "人間味", summary: "人間らしい温かさと感情的つながりの質。", tags: ["感情", "関係性", "倫理"],
    entries: {
      l0: "人間味とは人間存在の本質的な温かさ・共感能力が顕現する根源的位相である。生の感情の発露が人間存在を他の存在から際立たせる。",
      l1: "機械的効率か人間味かという選択。どの程度人間味を優先するかという判断の分岐が存在し、テクノロジー社会における人間性の位置づけが問われる。",
      l2: "感情の発生→表現→他者への伝達→共感という時間的因果連鎖。人間味ある関係が段階的に構築され、継続的な気づかいが信頼を育む。",
      l3: "温かさ・優しさ・共感という感情が中核にある。人間味は本質的に主観的感情体験に根ざしており、感受性と脆弱性の開示がその基盤となる。",
      l4: "人間味のある行動は社会的に高く評価される。冷淡さ・非人間的態度は批判される社会規範があり、AIとの比較で人間味の意義が問い直されている。",
      l5: "ハラスメント防止規定・労働基準法・福祉法など人間味ある扱いを制度的に保護する法律が存在する。尊厳の法的保護が人間味の制度的基盤を形成する。",
    },
  },
  {
    slug: "souzousei", titleJa: "創造性", summary: "新しいものを生み出す能力と創造のプロセス。", tags: ["アート", "イノベーション", "心理"],
    entries: {
      l0: "創造性とは存在しなかったものを世界に出現させる根源的能力である。無からの創造ではなく、既存の要素の新たな結合が創造の発生位相を形成する。",
      l1: "何を創るか、どう創るかという選択の空間が創造性の場を形成する。無数の可能性の中から特定の組み合わせを選ぶ能力が創造的選択の本質である。",
      l2: "創造は準備→インキュベーション→洞察→検証という段階的プロセスを経る。試行錯誤の連鎖が創造物を洗練させ、失敗から学ぶことが創造のプロセスに組み込まれる。",
      l3: "創造への衝動・フロー体験・完成の喜び・批判への不安が創造の心理的側面を形成する。内発的動機が高い創造性と関連し、評価への恐れが創造を妨げる場合がある。",
      l4: "独自性・革新性・美的価値が創造物の社会的評価基準となる。天才性・独創性への称賛と模倣・剽窃への批判が創造性の社会的位置づけを規定する。",
      l5: "著作権・特許権・商標権が創造物の法的保護を提供する。知的財産制度が創造のインセンティブを維持し、文化・技術の発展を制度的に支援する。",
    },
  },
  {
    slug: "byodou", titleJa: "平等", summary: "人々が等しく扱われるべきという規範的主張。", tags: ["社会", "政治", "倫理"],
    entries: {
      l0: "平等とは存在としての人間の根源的同一性に基づく価値概念である。すべての人間が等しく尊厳を持つという存在論的主張が平等の発生位相を形成する。",
      l1: "形式的平等か実質的平等か、機会の平等か結果の平等かという根本的選択がある。どの平等観を採るかという分岐が政策と制度設計の方向を決定する。",
      l2: "不平等→抵抗→変革→新たな平等の実現という歴史的因果連鎖。平等の拡大は闘争のプロセスを経て達成され、達成された平等が新たな不平等の発見を促す。",
      l3: "不平等への怒り、差別された経験への傷つき、平等実現への希望が平等の心理的側面を形成する。公正感覚の侵害が強い感情的反応を引き起こす。",
      l4: "平等は現代社会の中心的価値の一つである。差別・格差・特権への批判が社会規範として定着し、多様性と包摂が新たな評価基準として浮上している。",
      l5: "平等権は憲法・人権法・差別禁止法によって保障される。雇用均等法・障害者差別解消法・LGBTQ権利法が制度的に平等を具体化する。",
    },
  },
  {
    slug: "kindness", titleJa: "親切", summary: "他者への思いやりと助けの行為。", tags: ["倫理", "関係", "心理"],
    entries: {
      l0: "親切とは他者の存在への根源的な開放性と応答性が顕現する位相である。自己中心性を超えて他者の必要に向かう存在様式が親切の発生基盤を形成する。",
      l1: "助けるかどうか、どう助けるかという選択が常に存在する。見返りを求めるか求めないか、どの程度関与するかという分岐が親切の様態を決定する。",
      l2: "困難の認識→共感→行動→受け取り→感謝という時間的連鎖。親切な行為が連鎖反応を生み、返報性の原理が親切の社会的伝播を促進する。",
      l3: "共感・思いやり・他者への配慮が親切の感情的基盤を形成する。人助けの喜び・承認欲求・義務感が親切行為の動機となる心理的複雑さがある。",
      l4: "親切は社会的に高く評価される徳目である。見知らぬ人への親切・弱者への配慮が称賛され、冷淡さや無関心は批判の対象となる社会規範がある。",
      l5: "ボランティア活動・社会福祉制度・ケアワーク政策が親切を制度化する。ハラスメント規制が親切の境界を法的に定め、強制的善行の問題も生じている。",
    },
  },
  {
    slug: "songen", titleJa: "尊厳", summary: "人間の固有の価値と尊重されるべき地位。", tags: ["倫理", "人権", "哲学"],
    entries: {
      l0: "尊厳とは人間存在の根源的な内在的価値であり、いかなる条件にも依存しない固有の重要性の位相である。存在することそのものが尊厳の基盤を形成する。",
      l1: "尊厳を守るかどうかという選択が個人・組織・社会に常に問われる。尊厳の侵害に抵抗するか従うか、どの形で尊厳を主張するかという分岐がある。",
      l2: "尊厳の侵害→認識→抵抗→回復というプロセスが個人と社会のレベルで展開する。歴史的に尊厳の概念が拡張されてきた過程が人権の発展を形成してきた。",
      l3: "尊厳は自己価値感・誇り・恥辱感と深く結びついている。尊厳が傷つけられた時の怒りと痛み、尊厳が守られた時の安心が尊厳の心理的側面を形成する。",
      l4: "人間の尊厳の尊重は現代倫理の中心原理である。人を手段としてのみ扱うことへの批判、尊厳を傷つける行為への社会的非難が強く機能している。",
      l5: "尊厳は憲法・人権条約・生命倫理指針によって法的に保護される。尊厳死の権利・医療における自律尊重・拷問禁止が制度的に尊厳を守る枠組みを形成する。",
    },
  },
  {
    slug: "risuku", titleJa: "リスク", summary: "不確実性と潜在的損失の評価と管理。", tags: ["経済", "意思決定", "心理"],
    entries: {
      l0: "リスクとは存在の脆弱性と変化可能性から根源的に生まれる不確実性の位相である。未来の不確定性がリスクの発生基盤を形成し、完全なリスクゼロは存在しない。",
      l1: "リスクを取るかどうか、どの程度のリスクを受け入れるかという選択が常に問われる。回避・転嫁・保有・低減という選択肢がリスクマネジメントの基本分岐を形成する。",
      l2: "リスクは顕在化→損失発生→対応→回復（または失敗）という時間的連鎖を経る。リスクの相互関連が連鎖的損失をもたらし、システミックリスクが全体に波及する。",
      l3: "リスク感覚は高度に主観的である。損失回避バイアス・ゼロリスク幻想・楽観バイアスが合理的リスク評価を歪める。リスクへの恐怖と冒険心の葛藤が心理的課題となる。",
      l4: "リスクテイクへの社会的評価は文脈によって異なる。起業のリスクは称賛され、無謀なリスクは批判される。リスク情報の開示が社会的規範として求められる。",
      l5: "リスクは金融規制・保険法・安全規制・環境影響評価によって制度的に管理される。リスク開示義務・内部統制・規制資本要件が法的枠組みを形成する。",
    },
  },
];

export async function POST() {
  const admin = await requireAdmin();
  if (!isAuthUser(admin)) return admin;

  try {
    // Upsert layers
    const layerMap: Record<string, string> = {};
    for (const layer of layers) {
      const record = await prisma.layerDefinition.upsert({
        where: { slug: layer.slug },
        update: { nameJa: layer.nameJa, descriptionJa: layer.descriptionJa, colorClass: layer.colorClass },
        create: layer,
      });
      layerMap[layer.slug] = record.id;
    }

    // Upsert dictionary terms
    let dictCount = 0;
    for (const term of dictionaryTerms) {
      const existing = await prisma.dictionaryTerm.findFirst({
        where: { layerId: layerMap[term.layerSlug], term: term.term },
      });
      if (!existing) {
        await prisma.dictionaryTerm.create({
          data: {
            layerId: layerMap[term.layerSlug],
            term: term.term,
            weight: term.weight,
            isNegation: term.isNegation ?? false,
          },
        });
        dictCount++;
      }
    }

    // Upsert mapping rules
    const existingRules = await prisma.mappingRule.count();
    if (existingRules === 0) {
      await prisma.mappingRule.createMany({
        data: [
          { fromLayerId: layerMap["l3"], toLayerId: layerMap["l4"], pattern: "感情", replacement: "社会的表現", condition: "score_l3 > 0.5", priority: 10 },
          { fromLayerId: layerMap["l4"], toLayerId: layerMap["l5"], pattern: "規範", replacement: "法的規定", condition: "score_l4 > 0.4", priority: 8 },
          { fromLayerId: layerMap["l0"], toLayerId: layerMap["l2"], pattern: "生成", replacement: "プロセス展開", priority: 5 },
          { fromLayerId: layerMap["l1"], toLayerId: layerMap["l3"], pattern: "選択", replacement: "意図的選好", priority: 6 },
          { fromLayerId: layerMap["l2"], toLayerId: layerMap["l4"], pattern: "因果", replacement: "社会的帰責", condition: "score_l2 > 0.4", priority: 7 },
          { fromLayerId: layerMap["l3"], toLayerId: layerMap["l5"], pattern: "欲求", replacement: "権利主張", condition: "score_l3 > 0.6", priority: 9 },
        ],
      });
    }

    // Upsert concepts
    let conceptCount = 0;
    for (const concept of concepts) {
      const { entries, ...conceptData } = concept;
      const created = await prisma.concept.upsert({
        where: { slug: conceptData.slug },
        update: { titleJa: conceptData.titleJa, summary: conceptData.summary, tags: conceptData.tags, isPublished: true },
        create: { ...conceptData, isPublished: true },
      });
      conceptCount++;

      for (const [layerSlug, content] of Object.entries(entries)) {
        if (!layerMap[layerSlug]) continue;
        await prisma.layerEntry.upsert({
          where: { conceptId_layerId: { conceptId: created.id, layerId: layerMap[layerSlug] } },
          update: { content },
          create: { conceptId: created.id, layerId: layerMap[layerSlug], content },
        });
      }
    }

    // Pack version
    await prisma.packVersion.upsert({
      where: { key: "core" },
      update: { version: 2 },
      create: { key: "core", version: 2 },
    });

    const totalDict = await prisma.dictionaryTerm.count();
    const layerCount = await prisma.layerDefinition.count();

    return NextResponse.json({ ok: true, conceptCount, dictCount: totalDict, layerCount });
  } catch (e) {
    console.error("Seed error:", e);
    return NextResponse.json({ error: String(e) }, { status: 500 });
  }
}
